# Managed services
version: '3.2'
services:
  kafka:
    image: ubuntu/kafka
    ports:
      - 29092:29092
    environment:
      CREATE_TOPICS_COMMAND: "kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic user"