# Managed services
version: '3.2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: ubuntu/kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      CREATE_TOPICS_COMMAND: "kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic user"